## Mudança do US antigo para o novo modificado

In [1]:
import pandas as pd
import os

In [2]:
df_USA = pd.read_csv('United States_US_antigo.csv')

In [3]:
df_s_duplicatas = df_USA.drop_duplicates(subset='Date', keep='first')

In [4]:
df_s_duplicatas

,Date,Name,Type,Country Name,Country Code
0,2023-01-01,New Year's Day,['Local holiday'],United States,US
5,2023-01-02,New Year's Day (substitute),['Local holiday'],United States,US
9,2023-01-03,Asarah B'Tevet,['Hebrew'],United States,US
10,2023-01-04,World Braille Day,['United Nations observance'],United States,US
11,2023-01-06,Epiphany,['Christian'],United States,US
...,...,...,...,...,...
616,2023-12-24,Christmas Eve,['Local holiday'],United States,US
619,2023-12-25,Christmas Day,"['Local holiday', 'Christian']",United States,US
626,2023-12-26,Kwanzaa (first day),['Observance'],United States,US
629,2023-12-27,International Day of Epidemic Preparedness,['United Nations observance'],United States,US
630,2023-12-31,New Year's Eve,['Observance'],United States,US

In [5]:
df_s_duplicatas.to_csv('United States_US.csv', index=False)

## Junção dos CSV

In [7]:
import os

pasta_datasets = '/Users/thaysalima/Desktop/RePrograma./Python Fundamentos e análise de dados/Aula15 11.11/on26-python-s15-visualizacao-de-dados/exercicios/para-casa/paises_escolhidos'


dataframes = []


for arquivo in os.listdir(pasta_datasets):
    if arquivo.endswith('.csv'):
       
        caminho_arquivo = os.path.join(pasta_datasets, arquivo)
        df = pd.read_csv(caminho_arquivo)
        dataframes.append(df)


df_final = pd.concat(dataframes, ignore_index=True)


df_final.to_csv('/Users/thaysalima/Desktop/RePrograma./Python Fundamentos e análise de dados/Aula15 11.11/on26-python-s15-visualizacao-de-dados/exercicios/para-casa/atividade/feriados_2023.csv', index=False)

In [11]:
df_feriados = pd.read_csv('feriados_2023.csv')
df_feriados.describe()

,Date,Name,Type,Country Name,Country Code
count,691,691,691,691,691
unique,326,451,27,8,8
top,2023-08-07,New Year's Day,['United Nations observance'],United States,US
freq,10,8,126,273,273